version: "2.3"

services:
  build-book:
    image: jupyter/book:builder
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: builder
    command: echo "built" # This prevents the default command from running (i.e. jupyter notebook)
