version: "2.3"

services:
  run-nginx:
    build:
      context: ../nginx
      dockerfile: ../docker/Dockerfile.nginx
    restart: unless-stopped
    container_name: nginx
    links:
      - run-voila
    ports:
      - 80:80
    volumes:
      - ../nginx/conf.d/:/etc/nginx/conf.d/
