version: "2.3"

services:
  run-voila:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: deploy
      cache_from:
        - jupyter/book:builder
    volumes:
      - ../:/home/jovyan/work
    expose:
      - 8866
    command: ./run_voila
